services:
  - type: web
    name: ruquia-portfolio
    runtime: static
    buildCommand: ""
    staticPublishPath: ./portfolio
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
